version: "3"
services:
  app:
    image: node:8
    container_name: designer-server-app
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
    environment:
      - NODE_ENV=dev
    ports:
      - "3030:3030"
    links:
      - mongo
    command: "npm start"
  mongo:
    container_name: designer-server-mongo
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27018:27018"
    command: ["--bind_ip_all"]
  nginx:
    image: nginx:latest
    container_name: designer-server-nginx
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - app
    environment:
      - VIRTUAL_HOST=designer-server.breezemakes.com
  admin:
    image: mongo-express
    container_name: designer-server-mongo-express
    ports:
      - "8089:8081"
    links:
      - mongo:mongo
  nginx2:
    image: nginx:latest
    container_name: designer-server-mongo-express-nginx
    volumes:
      - ./nginx/admin.conf:/etc/nginx/conf.d/site.conf
    links:
      - admin
    environment:
      - VIRTUAL_HOST=designer-server-mongo-express.breezemakes.com
networks:
  default:
    external: 
      name: nginx-proxy-network